echo ''
echo '*********'
echo 'scanning'
echo '*********'
echo ''
arp-scan -l
echo ''
echo '---------------'
echo 'scan completed'
echo '---------------'
echo ''
echo '----------------------------------------------------'
echo 'DONT FORGET RUN THIS COMMAND AS ROOT'
echo '----------------------------------------------------'
echo 'to start killing type : python kill.py [TARGET IP]'
echo '----------------------------------------------------'
echo 'example : python kill.py 192.168.1.3'
echo '----------------------------------------------------'
echo 'Warning : All responsibility of using this application goes to user'
echo '----------------------------------------------------'
echo ''
echo ''